# require:
#   - rubocop-rails
#   - rubocop-minitest
# AllCops:
#   NewCops: enable
#   Include:
#     - app/**/*.rb
#     - lib/**/*.rb
#     - test/**/*test.rb
# convention:Style/FrozenStringLiteralComment:
#   Enabled: true
