AllCops:
  SuggestExtensions:
    rubocop-rake: false
require:
  - rubocop-rails
Style/Documentation:
  Enabled: false
convention:Style/FrozenStringLiteralComment:
  Enabled: true
Layout/LineLength:
  Max: 170
